"""Turn a trajectory into a module the hub can import.

The SPIKE Prime hub has no filesystem, so a program cannot open() a trajectory
while it is running. The data has to arrive as a Python module that Pybricks
bundles alongside the program at download time.

That conversion has lived in the quick-start repo as tools/txt_to_py.py, a
second step the team runs by hand after exporting a .txt. This does the same
job in one step, straight from the trajectory, which is what lets the web
planner hand somebody a finished file to download.

The output is deliberately identical to what txt_to_py.py produces, apart from
the first line saying where it came from -- tests/test_hub_module.py checks
that against the module currently on the hub.

Format:
    STEPS   int, ms per state
    MARKERS tuple[int], marker timestamps in ms
    COUNT   int, number of expanded states
    DATA    bytes, COUNT * 3 little-endian int16:
            left * 100, right * 100, heading * 10

DATA is one bytes constant rather than a list of numbers on purpose: a list of
several thousand ints would be compiled into bytecode and boxed individually on
the hub's small heap, while a bytes literal stays one compact object that
struct.unpack_from can index in place.
"""

import struct


# int16 range; powers scale by 100 (0.01% resolution), heading by 10 (0.1 deg).
POWER_SCALE = 100
HEAD_SCALE = 10
INT16_MIN, INT16_MAX = -32768, 32767

STATE_FORMAT = "<hhh"
BYTES_PER_LINE = 24


def _clamp(value: int, name: str, source: str) -> int:
    if not INT16_MIN <= value <= INT16_MAX:
        raise ValueError(
            "{0}: scaled {1} value {2} does not fit in an int16".format(
                source, name, value))
    return value


def _bytes_literal(payload, per_line: int = BYTES_PER_LINE) -> str:
    """Render the payload as chunked, implicitly concatenated bytes literals."""
    chunks = []

    for start in range(0, len(payload), per_line):
        chunks.append("    " + repr(bytes(payload[start:start + per_line])))

    return "\n".join(chunks)


def hub_payload(generator, name: str = "trajectory", steps: int = 1):
    """Pack the run into bytes, two drive motors at a time.

    The powers are rounded to two decimals before being scaled, because that is
    what the .txt export writes and therefore what the hub has always been fed.
    Skipping that rounding would shift the occasional value by one unit.
    """
    payload = bytearray()
    count = 0

    for wheel_states, head, copies in generator.wheel_speed_groups(steps):
        if not len(wheel_states) == 2:
            raise ValueError(
                "{0}: the hub format carries two drive motors, but this robot "
                "has {1} wheels. Only a tank drive can be exported this way."
                .format(name, len(wheel_states)))

        powers = [round(generator.robot.to_motor_power(state.VELOCITY), 2)
                  for state in wheel_states]

        left = _clamp(round(powers[0] * POWER_SCALE), "left", name)
        right = _clamp(round(powers[1] * POWER_SCALE), "right", name)
        heading = _clamp(round(round(head, 2) * HEAD_SCALE), "heading", name)

        payload += struct.pack(STATE_FORMAT, left, right, heading) * copies
        count += copies

    return payload, count


def hub_module_text(generator, name: str = "trajectory", steps: int = 1) -> str:
    """The text of a module the hub can import, ready to be saved."""
    markers = tuple(int(marker.time) for marker in generator.MARKERS)
    payload, count = hub_payload(generator, name, steps)

    return (
        '"""{0}, generated by PythFinder -- do not edit."""\n'
        "\n"
        "STEPS = {1}\n"
        "MARKERS = {2}\n"
        "COUNT = {3}\n"
        "\n"
        "# {3} states * 3 little-endian int16 (left*100, right*100, head*10)\n"
        "DATA = (\n{4}\n)\n"
    ).format(name, steps, markers, count, _bytes_literal(payload))
