#!/usr/bin/env python3
"""
Convert a PythFinder trajectory export into a Pybricks-importable module.

The SPIKE / Prime hub has no filesystem, so `open()` is unavailable inside a
running program. Trajectory data therefore has to arrive as a Python module
that Pybricks bundles alongside the main program at download time.

Input format (as produced by PythFinder, see Trajectory/TXT/*.txt):
    line 1: marker timestamps, space separated (may be blank)
    line 2: step size in ms
    line 3: flat run-length-encoded quads of
            <left power> <right power> <heading deg> <consecutive copies>

Output format (traj_<name>.py):
    STEPS   int, ms per state
    MARKERS tuple[int], marker timestamps in ms
    COUNT   int, number of expanded states
    DATA    bytes, COUNT * 3 little-endian int16:
            left * 100, right * 100, heading * 10

DATA is a single bytes constant rather than a list literal on purpose: a list
of ~4000 ints would be compiled into bytecode and boxed individually on the
hub's small heap, while a bytes literal stays one compact object that
struct.unpack_from can index in place.

Usage:
    python3 tools/txt_to_py.py Trajectory/TXT/test.txt
    python3 tools/txt_to_py.py Trajectory/TXT/*.txt --outdir .
"""

import argparse
import os
import struct
import sys

# int16 range; powers scale by 100 (0.01% resolution), heading by 10 (0.1 deg).
POWER_SCALE = 100
HEAD_SCALE = 10
INT16_MIN, INT16_MAX = -32768, 32767


def _clamp(value, name, source):
    if not INT16_MIN <= value <= INT16_MAX:
        raise ValueError(
            "{0}: scaled {1} value {2} does not fit in an int16".format(
                source, name, value
            )
        )
    return value


def parse(path):
    with open(path, "r") as handle:
        lines = handle.read().split("\n")

    # Blank leading lines are common in the exports; keep the first three
    # meaningful ones but preserve a genuinely empty marker line.
    if len(lines) < 3:
        raise ValueError("{0}: expected at least 3 lines".format(path))

    markers = tuple(int(each) for each in lines[0].split())
    steps = int(lines[1])
    fields = lines[2].split()

    if len(fields) % 4:
        raise ValueError(
            "{0}: state line holds {1} values, not a multiple of 4".format(
                path, len(fields)
            )
        )

    payload = bytearray()
    count = 0

    for i in range(0, len(fields), 4):
        left = _clamp(round(float(fields[i]) * POWER_SCALE), "left", path)
        right = _clamp(round(float(fields[i + 1]) * POWER_SCALE), "right", path)
        head = _clamp(round(float(fields[i + 2]) * HEAD_SCALE), "heading", path)
        copies = int(fields[i + 3])

        payload += struct.pack("<hhh", left, right, head) * copies
        count += copies

    return steps, markers, count, payload


def _bytes_literal(payload, per_line=24):
    """Render payload as chunked, implicitly concatenated bytes literals."""
    chunks = []
    for start in range(0, len(payload), per_line):
        chunks.append("    " + repr(bytes(payload[start:start + per_line])))
    return "\n".join(chunks)


def render(name, steps, markers, count, payload):
    return (
        '"""Generated by tools/txt_to_py.py from {0}.txt -- do not edit."""\n'
        "\n"
        "STEPS = {1}\n"
        "MARKERS = {2}\n"
        "COUNT = {3}\n"
        "\n"
        "# {3} states * 3 little-endian int16 (left*100, right*100, head*10)\n"
        "DATA = (\n{4}\n)\n"
    ).format(name, steps, markers, count, _bytes_literal(payload))


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("inputs", nargs="+", help="PythFinder .txt export(s)")
    parser.add_argument(
        "--outdir", default=".", help="where to write traj_<name>.py (default: .)"
    )
    args = parser.parse_args(argv)

    for path in args.inputs:
        name = os.path.splitext(os.path.basename(path))[0]
        steps, markers, count, payload = parse(path)

        out = os.path.join(args.outdir, "traj_{0}.py".format(name))
        with open(out, "w") as handle:
            handle.write(render(name, steps, markers, count, payload))

        print(
            "{0} -> {1}\n"
            "    {2} states, {3} ms step, {4:.1f}s total\n"
            "    {5} markers, {6} bytes on the hub".format(
                path, out, count, steps, count * steps / 1000.0,
                len(markers), len(payload),
            )
        )

    return 0


if __name__ == "__main__":
    sys.exit(main())
