"""run_a, generated by PythFinder -- do not edit."""

from pybricks.parameters import Stop
from pybricks.tools import wait


def _action_1(core):
    """arm down"""
    pass        # nothing bound to this one yet


def _action_2(core):
    """arm up"""
    pass        # nothing bound to this one yet


def run(core):
    """Drive this run. The only thing runs.py needs to call."""
    drive = core.configure()
    core.set_heading(0)

    drive.straight(350, then=Stop.NONE)
    _action_1(core)        # arm down
    drive.straight(400)
    wait(600)
    core.turn_to(90, 90)
    drive.straight(290, then=Stop.NONE)
    _action_2(core)        # arm up
    drive.straight(10)
    core.turn_to(201.8, 111.8)
    drive.straight(807.8)
    core.turn_to(0, 158.2)

    core.stopTaskMotors()
